version: '3.8'

services:
  flexicaf:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flexicaf_app
    restart: unless-stopped
    ports:
      - "8080:80" # Tu pourras accéder à l'app sur http://localhost:8080
    volumes:
      # On map le dossier local db vers le dossier db du conteneur
      - ./src/db:/var/www/html/db
