version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: flexiCAF
    ports:
      - "7000:80"
    volumes:
      # Code source de l'application
      - /home/rocky/flexiCAF/src:/var/www/html
    restart: unless-stopped
